apiVersion: v1
kind: PersistentVolume
metadata:
  name: test-node-volume
  namespace: test
spec:
  capacity:
    storage: 100Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  storageClassName: test-local-storage
  local:
    path: /mysql/data
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: nodeLabel
          operator: In
          values:
          - mynode
---

apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: test-local-storage
  namespace: test
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: Immediate

---

kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: test-node-volume-claim
  namespace: test
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: test-local-storage
  resources:
    requests:
      storage: 99Gi