apiVersion: v1
kind: ConfigMap
metadata:
  name: demo-page-config
  namespace: demo
  labels:
    app: wf-demo-page
data:
    constant.js: |
      var DOMAIN_API_URL = "another-url";


---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: wf-demo-page
  namespace: demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wf-demo-page
      version: v1
  template:
    metadata:
      labels:
        app: wf-demo-page
        version: v1
    spec:
      containers:
      - name: wf-demo-page
        image: nginx:latest
        imagePullPolicy: Always
        resources:
          requests:
            memory: "100Mi"
            cpu: "50m"
          limits:
             memory: "300Mi"
             cpu: "100m"   
        ports:
        - containerPort: 80
          protocol: TCP
        volumeMounts:
          - name:  demo-config-volume
            mountPath:  /usr/share/nginx/html/js/constant.js
            subPath: constant.js
      volumes:
      - name: demo-config-volume
        configMap:
          name: demo-page-config                
---

kind: Service
apiVersion: v1
metadata:
  name: wf-demo-page
  namespace: demo
spec:
  type: NodePort
  selector:
    app: wf-demo-page
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 32067
