apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: first-binding
  namespace: default #default namespace
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: admin-access
subjects:
- kind: ServiceAccount
  name: dev-multiple-ns
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: second-binding 
  namespace: second #second namespace
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: admin-access
subjects:
- kind: ServiceAccount
  name: dev-multiple-ns
  namespace: default
