kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: admin-access
rules:
- apiGroups: ["", "extensions", "apps","*"]
  resources: ["*"]
  verbs: ["*"]
- apiGroups: ["batch"]
  resources:
  - jobs
  - cronjobs
  verbs: ["*"]
